site_name: Faust Libraries 

nav:
    - Home: index.md
    - Introduction:
         - ' Overview ':  using.md
         - ' Standard Functions ':  standardFunctions.md
         - ' Primitives ':  primitives.md
        
    - Libraries:
         - ' analyzers ':  libs/analyzers.md
         - ' basics ':  libs/basics.md
         - ' compressors ':  libs/compressors.md
         - ' delays ':  libs/delays.md
         - ' demos ':  libs/demos.md
         - ' dx7 ':  libs/dx7.md
         - ' envelopes ':  libs/envelopes.md
         - ' filters ':  libs/filters.md
         - ' hoa ':  libs/hoa.md
         - ' interpolators ':  libs/interpolators.md
         - ' maths ':  libs/maths.md
         - ' misceffects ':  libs/misceffects.md
         - ' oscillators ':  libs/oscillators.md
         - ' noises ':  libs/noises.md
         - ' phaflangers ':  libs/phaflangers.md
         - ' physmodels ':  libs/physmodels.md
         - ' reducemaps ':  libs/reducemaps.md
         - ' reverbs ':  libs/reverbs.md
         - ' routes ':  libs/routes.md
         - ' signals ':  libs/signals.md
         - ' soundfiles ':  libs/soundfiles.md
         - ' spats ':  libs/spats.md
         - ' synths ':  libs/synths.md
         - ' vaeffects ':  libs/vaeffects.md

markdown_extensions:
    - toc:
        baselevel: 1

site_dir: ../docs
  
extra_css:
    - css/extra.css
    
